In [1]:
import numpy as np
import plotly.express as px
import pandas as pd
import time
from datetime import timedelta

In [2]:
# Load the data into different dataframes
arm_cpu       = pd.read_csv('arm_cpu.csv')
arm_mem       = pd.read_csv('arm_memory.csv')
arm_network   = pd.read_csv('arm_network.csv')

#Set time as index
arm_cpu['Time'] = [timedelta(seconds=i * 15).__str__() for i in range(len(arm_cpu))]
arm_cpu.set_index('Time', inplace=True)
arm_cpu = arm_cpu.apply(lambda x: x/10000000) # Convert to CPU percentage
arm_cpu["Combined"] = arm_cpu[arm_cpu.keys()].sum(axis=1)

#Set time as index
arm_mem['Time'] = [timedelta(seconds=i * 15).__str__() for i in range(len(arm_mem))]
arm_mem.set_index('Time', inplace=True)
arm_mem = arm_mem.apply(lambda x: x/1000) # Convert to MB
arm_mem["Combined"] = arm_mem[arm_mem.keys()].sum(axis=1)


#Set time as index
arm_network['Time'] = [timedelta(seconds=i * 15).__str__() for i in range(len(arm_network))]
arm_network.set_index('Time', inplace=True)
arm_network = arm_network.apply(lambda x: x/1000000) # Convert to MB
arm_network["Combined"] = arm_network[arm_network.keys()].sum(axis=1)

# Lightweight platform
### CPU

In [3]:
arm_cpu.head()

,ditto-connectivity,ditto-gateway,ditto-nginx,ditto-policies,ditto-things,ditto-thingssearch,ot-mongodb,mosquitto,Combined
Time,,,,,,,,,
0:00:00,10.238843,9.142974,0.0,7.355340,10.022407,5.038642,1.067600,0.057586,42.923392
0:00:15,9.215631,9.344560,0.0,7.089132,6.998499,5.376201,1.037381,0.058181,39.119586
0:00:30,10.319213,8.273940,0.0,5.849545,9.580272,5.894031,1.114047,0.058728,41.089774
0:00:45,9.012832,8.207336,0.0,6.778831,8.458514,6.052959,1.037256,0.057376,39.605105
0:01:00,8.652139,7.403161,0.0,7.564309,6.521371,6.054159,1.084659,0.057300,37.337099

In [4]:
# Plot using plotly
fig = px.line(arm_cpu, x=arm_cpu.index, y=arm_cpu.keys(), title='CPU Usage %')
fig.show()

### Memory

In [5]:
arm_mem.head()

,ditto-connectivity,ditto-gateway,ditto-nginx,ditto-policies,ditto-things,ditto-thingssearch,ot-mongodb,mosquitto,Combined
Time,,,,,,,,,
0:00:00,751.54080,436.67920,4.64672,472.67000,561.14032,589.84240,112.50176,3.1616,2932.18280
0:00:15,549.37784,436.10720,3.62560,515.12256,515.62272,421.44880,80.35920,3.1616,2524.82552
0:00:30,499.58400,523.33536,5.45760,515.22912,430.22720,463.74680,78.42240,2.4320,2518.43448
0:00:45,749.98560,480.10864,5.45640,558.28864,559.70824,421.75760,86.40280,2.6752,2864.38312
0:01:00,649.32088,610.34176,4.72888,472.45616,558.68280,506.15136,78.75040,3.4048,2883.83704

In [6]:
# Plot using plotly
fig = px.line(arm_mem, x=arm_mem.index, y=arm_mem.keys(), title='Memory Usage mb')
fig.show()

### Network

In [7]:
arm_network.head()

,ot-ditto-connectivity-d48b6b9cc-sft9c,ot-ditto-gateway-86dddd6974-gmrdf,ot-ditto-nginx-b68ddf755-jf46g,ot-ditto-policies-669b4cf5d5-h4mq5,ot-ditto-things-58c8749899-pz2j6,ot-ditto-thingssearch-cf557f87c-kwl9z,ot-mongodb-c6547b44c-jmrbz,ot-mosquitto-7b79d8d467-88b8n,Combined
Time,,,,,,,,,
0:00:00,0.146142,0.290067,0.000000,0.131200,0.117316,0.084545,0.010659,0.000544,0.780473
0:00:15,0.217227,0.165943,0.000342,0.162097,0.227168,0.088127,0.010062,0.001430,0.872396
0:00:30,0.173575,0.107117,0.000000,0.137083,0.096644,0.062615,0.000000,0.000544,0.577578
0:00:45,0.121900,0.156839,0.000000,0.142471,0.175657,0.170717,0.010140,0.000000,0.777724
0:01:00,0.146246,0.202715,0.000000,0.145040,0.122263,0.102004,0.012593,0.001808,0.732669

In [8]:
# Plot using plotly
fig = px.line(arm_network, x=arm_network.index, y=arm_network.keys(), title='Network Usage mb')
fig.show()

### Combining total measurements into one dataset

In [9]:
# Combine one column from each dataframe into a new dataframe
# Select the desired columns from each dataframe
column_cpu = arm_cpu['Combined']
column_mem = arm_mem['Combined']
column_network = arm_network['Combined']

# Combine the selected columns into a new dataframe
combined_df = pd.concat([column_cpu, column_mem, column_network], axis=1)
combined_df.columns = ['CPU', 'Memory', 'Network']
combined_df['Time'] = combined_df.index
# combined_df.set_index('Time', inplace=True)
# Print the combined dataframe
print(combined_df)

combined_df.to_csv('arm_combined.csv', index=False)

               CPU      Memory   Network     Time
Time
0:00:00  42.923392  2932.18280  0.780473  0:00:00
0:00:15  39.119586  2524.82552  0.872396  0:00:15
0:00:30  41.089774  2518.43448  0.577578  0:00:30
0:00:45  39.605105  2864.38312  0.777724  0:00:45
0:01:00  37.337099  2883.83704  0.732669  0:01:00
...            ...         ...       ...      ...
0:14:00  29.781346  2892.65936  0.521945  0:14:00
0:14:15  29.209400  3044.60512  0.739607  0:14:15
0:14:30  31.228323  2812.96496  0.924005  0:14:30
0:14:45  29.874054  2892.70016  0.598598  0:14:45
0:15:00  30.465867  2552.07304  0.636114  0:15:00

[61 rows x 4 columns]